apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "productapi.labels" . | nindent 4 }}
  name:  {{ .Values.service.name | quote }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "productapi.selectorLabels" . | nindent 4 }}
    type: {{ .Values.service.type }}

