# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - Microservices/ProductAPI/*
    - Microservices/ProductAPI-Deployment.yaml

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'ACRRegistryConnection'
  imageRepository: 'productapi'
  containerRegistry: 'onlineshopping22acr.azurecr.io'
  dockerfilePath: 'ProductAPI/Dockerfile'
  tag: '$(Build.BuildId)'
  deploymentFile: 'ProductAPI-Deployment.yaml'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  

stages:
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build the container image
      inputs:
        command: build
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        buildContext: $(Build.SourcesDirectory)
        tags: |
          $(tag)


          CmdLine@2
            displayName: Scan for reports
            inputs:
              script: |
                docker run --rm \
                -v /var/run/docker.sock:/var/run/docker.sock \
                -v $HOME/Library/Caches:/root/.cache/ \
                -v "$(pwd):/src" \
                aquasec/trivy \
                --exit-code 0 \
                --severity LOW,MEDIUM,HIGH \
                --format template --template "@contrib/junit.tpl" \
                -o src/junit-report-low-med-high.xml \
                --ignore-unfixed \
                '$(imageRepository):$(tag)'
                 
                docker run --rm \
                -v /var/run/docker.sock:/var/run/docker.sock \
                -v $HOME/Library/Caches:/root/.cache/ \
                -v "$(pwd):/src" \
                aquasec/trivy \
                --exit-code 0 \
                --severity CRITICAL \
                --format template --template "@contrib/junit.tpl" \
                -o src/junit-report-crit.xml \
                --ignore-unfixed \
                '$(imageRepository):$(tag)'
          - task: PublishTestResults@2
            displayName: Publish Test Results
            inputs:
              testResultsFormat: "JUnit" # Options: JUnit, NUnit, VSTest, xUnit, cTest
              testResultsFiles: "**/junit-report-*.xml"
    - task: Docker@2
      displayName: Push the image to container registry
      inputs:
        command: push
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        buildContext: $(Build.SourcesDirectory)
        tags: |
          $(tag)
- stage: Deploy
  displayName: Deploy to k8s
  jobs:  
  - job: Deploy
    displayName: Deploy to k8s
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: replacetokens@3
      inputs:
        rootDirectory: '$(Build.SourcesDirectory)'
        targetFiles: '$(deploymentFile)'
        encoding: 'auto'
        writeBOM: true
        actionOnMissing: 'warn'
        keepToken: false
        tokenPrefix: '#{'
        tokenSuffix: '}#'
        useLegacyPattern: false
        enableTelemetry: true
    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'AKSServiceConnection'
        namespace: 'default'
        command: 'apply'
        useConfigurationFile: true
        configuration: '$(Build.SourcesDirectory)/$(deploymentFile)'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'
        azureSubscriptionEndpointForSecrets: 'azureamol(42f01daf-7fb8-4db8-8fce-9af5dde90556)'
        azureContainerRegistry: 'onlineshopping22acr.azurecr.io'
        secretName: 'pullkey'